Remove obj client interface
pachyderm/pachyderm pull request #10116
Opened 2024-06-12 14:27 UTC by brycemcanally

This PR removes the `obj.Client` interface and all of the code associated with it. The `obj.Client` interface, and its corresponding implementations, is the legacy method of interfacing with object storage providers. This PR is a complete transition to using GoCDK for interfacing with object storage providers.

2024-06-12 17:06 UTC, FahadBSyed requested changes
Looks like CI is failing, you may need to rerun gazelle to update the dependencies.

Other than that, the code changes look great 👍

2024-06-13 17:56 UTC, FahadBSyed approved these changes

2024-06-13 19:06 UTC, jrockway approved these changes

2024-06-14 11:11 UTC, acohen4 approved these changes

2024-06-14 13:28 UTC, merged