Allow listing datums for pipelines before they exist.
pachyderm/pachyderm pull request #5394
Opened 2020-10-28 01:30 UTC by jdoliner

2020-11-02 20:14 UTC, PFedak reviewed
LGTM other than the one comment
I'm not sure I know how people use cron inputs - are there cases where it would provide value to to modify the provided input to ignore the cron and list the remaining datums?

2020-11-02 20:14 UTC, PFedak commented on src/server/pps/server/api_server.go
> +	if input != nil {
should this be an else if? The job if above sets input, and I assume we still want to allow listDatum for existing jobs with cron inputs

2020-11-02 21:43 UTC, Tryneus requested changes
Some nits, and this could probably use a sanity test in `src/server/pps/cmds/cmds_test.go`, but otherwise LGTM.

2020-11-02 21:43 UTC, Tryneus commented on src/client/pps.go
> +	}
nit: you could get rid of this `if` and `req` by having the function take a `job *pps.Job` instead of a `jobID string`

2020-11-02 21:43 UTC, Tryneus commented on src/client/pps.go
> +	}
same goes here

2020-11-02 21:43 UTC, Tryneus commented on src/server/pps/cmds/cmds.go
> +			} else {
there needs to be a similar error case for if _both_ `pipelineInputPath != ""` and `len(args) == 1` or else one of the options is silently discarded

2020-11-02 21:43 UTC, Tryneus commented on src/server/pps/cmds/cmds.go
> +	listDatum.Flags().StringVarP(&pipelineInputPath, "file", "f", "", "The JSON file containing the pipeline to list datums from, the pipeline need not exist.")
nit: the other flags don't use periods and this isn't a full sentence - drop the period

2020-11-03 18:32 UTC, jdoliner commented
> are there cases where it would provide value to to modify the provided input to ignore the cron and list the remaining datums?

Not really, the only case where you could have a cron without ticks and still have datums is if the cron is in a union or the newly added outer join. Neither of which really makes sense to me in terms of a use case. I think in the future I'll make it so we simulate a few ticks of the cron to return something useful in that case. But for this PR it seemed easier to punt on that and just get the core logic working.

2020-11-04 00:00 UTC, jdoliner commented
@PFedak @Tryneus alright think I addressed everything, another look whenever you get a chance.

2020-11-04 17:51 UTC, PFedak approved these changes
LGTM

2020-11-04 21:31 UTC, Tryneus approved these changes
LGTM

2020-11-04 23:59 UTC, merged