[ci skip] Doc loki
pachyderm/pachyderm pull request #5518
Opened 2020-12-10 20:59 UTC by nadegepepin

First version

2020-12-10 21:12 UTC, echohack requested changes
Just a few fixes around wording of forwarding. Sorry for not fixing this sooner!

2020-12-10 21:12 UTC, echohack commented on doc/docs/master/deploy-manage/deploy/loki.md
> +to forward logs to Loki,
forward -> ship

2020-12-10 21:12 UTC, echohack commented on doc/docs/master/deploy-manage/deploy/loki.md
> +can be modified to include log forwarding as follows:
can be modified to include log forwarding as follows: -> can be modified to make logs available for Loki as follows:

2020-12-10 21:21 UTC, echohack approved these changes
👍

2021-01-14 13:46 UTC, nadegepepin commented
Closing this PR - was merged as part of the 1.12.0 release PR #5534

2021-01-14 13:46 UTC, closed without merging