Allow moving a branch to an ancestor of its head.
pachyderm/pachyderm pull request #6465
Opened 2021-07-02 16:39 UTC by PFedak

2021-07-02 17:20 UTC, PFedak commented
Fix #6367

2021-07-07 17:51 UTC, Tryneus requested changes

2021-07-07 18:15 UTC, PFedak commented on src/internal/transactionenv/env.go
> +			if useOverride && overrideID != nil {
Ah of course, good point.

2021-07-07 18:33 UTC, PFedak commented on src/internal/transactionenv/env.go
> +
No, I was thinking it was kind of "about" transactions, but you're right that it's really a PFS level thing. I'll move it back

2021-07-07 18:54 UTC, Tryneus commented
LGTM

2021-07-07 18:54 UTC, Tryneus approved these changes

2021-07-07 19:19 UTC, merged