Rename dash to console
pachyderm/pachyderm pull request #6524
Opened 2021-07-13 14:30 UTC by chainlink

2021-07-13 18:45 UTC, armaanv requested changes
I think the TestconsoleImageAndConfigTag test will fail due to the wrong expected image tag. Looks like CI didn't run that test.

LGTM otherwise

2021-07-26 16:03 UTC, chainlink commented on etc/helm/test/pachyderm_helm_test.go
> +	expectedContainerImage := "pachyderm/haberconsoleery:abc123"
lol haberconsoleery

2021-07-26 18:44 UTC, armaanv commented on etc/helm/test/tls_test.go
> +	_, err := helm.RenderTemplateE(t, options, helmChartPath, "secret", []string{"templates/ingress/ingress.yaml"})
should this be console?

2021-07-26 20:22 UTC, chainlink commented on etc/helm/test/tls_test.go
> +	_, err := helm.RenderTemplateE(t, options, helmChartPath, "secret", []string{"templates/ingress/ingress.yaml"})
ingress has been moved to root

2021-07-26 20:37 UTC, armaanv approved these changes

2021-07-27 11:24 UTC, merged