Create a helper template for stable random values
pachyderm/pachyderm pull request #6691
Opened 2021-08-05 19:17 UTC by acohen4

In this solution, the current timestamp is used to compute a hash. 

There's an obvious, though probabilistically unlikely problem of having the time change between invocations of this template within the script, where the resulting hash wouldn't be stable.

2021-08-05 19:59 UTC, acohen4 commented
closes https://github.com/pachyderm/pachyderm/issues/6660

2021-08-10 16:54 UTC, chainlink commented on etc/helm/pachyderm/templates/_helpers.tpl
> +        {{- derivePassword 1 "long" (now | toString | trunc 16) .hashSalt "pachyderm" -}}
Can you add some docs here? (ie, talking about the date truncation, perhaps referencing the article we found this in.

2021-08-12 17:17 UTC, chainlink commented on etc/helm/pachyderm/templates/_helpers.tpl
> +{{- if .defaultValue }}
This method might be a little "too smart" for helm (specifically passing in a hash as an arg) Generally with helm it's ok to break DRY to make things more clear / use values directly.

2021-08-12 17:19 UTC, chainlink requested changes
This looks good, but we need a couple of changes on the testing side.

I think we should ship this PR, but the more I think about it, I think we should fix the root issue in the config pod before RC (being able to reference the secret values from Env vars/ secrets instead of embedding them in the config)

2021-08-16 20:50 UTC, closed without merging