Helm Auth Config with updated console
pachyderm/pachyderm pull request #6958
Opened 2021-09-29 21:09 UTC by acohen4

2021-09-29 21:10 UTC, acohen4 commented on etc/helm/examples/local-dev-values.yaml
> +  activateEnterprise: false
add this to doc....

2021-09-29 21:10 UTC, acohen4 commented on etc/helm/pachyderm/templates/pachd/config-secret.yaml
> +  # TODO: When should this _not_ be specified?
I think I can remove this entirely. It's supposed to serve as an example for pushing pachyderm Cluster Role bindings to pachd

2021-09-29 22:12 UTC, chainlink requested changes
First pass

2021-09-29 22:15 UTC, chainlink commented
Looks like we can totally eliminate the local-values.yaml file with this PR 🎉

2021-09-29 22:18 UTC, chainlink commented
Need to change the check in etc/helm/pachyderm/templates/pachd/config-job.yaml to `activateEnterprise` instead of `enterpriseLicenseKey`

2021-09-30 13:11 UTC, acohen4 commented on etc/helm/pachyderm/templates/pachd/config-secret.yaml
> +  # TODO: When should this _not_ be specified?
yeah sure. How does having this piece in a comment block sound?

2021-09-30 15:42 UTC, chainlink requested changes
One small change, but otherwise looks good

2021-09-30 15:42 UTC, chainlink commented on etc/helm/pachyderm/values.yaml
>      oauthPachdClientID: pachd
`oauthPachdClientID` should be removed

2021-09-30 15:44 UTC, chainlink commented
Can you add docs to both the helm docs and to the values.yaml file for the new fields?

2021-09-30 22:05 UTC, merged