Draw pach DAGs on the command line
pachyderm/pachyderm pull request #7304
Opened 2022-02-11 05:13 UTC by acohen4

2022-08-03 16:38 UTC, acohen4 commented on src/server/pps/pretty/draw.go
> +	layerVerticalSpace = 5
should we parameterize for CLI?

2022-09-14 22:28 UTC, albscui requested changes
Maybe split this into 2 PRs, where 1st PR does the PPS changes, and the 2nd is purely the draw stuff.

2022-09-14 22:28 UTC, albscui commented on src/server/pps/server/api_server.go
> +		if request.CommitSet != nil && request.CommitSet.ID != "" {
try request.GetCommitSet() instead

2022-09-27 15:19 UTC, albscui approved these changes
Overall LGTM, just a few nits on style.

2022-09-27 15:19 UTC, albscui commented on src/server/pps/pretty/draw.go
> +		return setEdgeChar(row, i, '\\')
Similarly
```suggestion
		return setEdgeChar(row, re.src + offset, '\\')
```
I prefer to un-nest this else and just return below the `if` block.

2022-09-27 19:07 UTC, merged