helm: enable proxy by default; add NOTE about externalService deprecation
pachyderm/pachyderm pull request #8434
Opened 2022-12-09 20:58 UTC by jrockway

This is CORE-1307.

2022-12-16 13:30 UTC, tybritten requested changes
LGTM, just that one typo

2022-12-16 13:30 UTC, tybritten commented on etc/helm/pachyderm/templates/NOTES.txt
> +    echo '{"pachd_address":"grpc://{{ .Values.proxy.host }}:443"}' | pachctl config set context {{ .Release.Name }} --overwrite && pachctl config set active-context {{ .Release.Name }}
```suggestion
    echo '{"pachd_address":"grpcs://{{ .Values.proxy.host }}:443"}' | pachctl config set context {{ .Release.Name }} --overwrite && pachctl config set active-context {{ .Release.Name }}
```
grpcs

2022-12-21 05:41 UTC, jrockway commented
PTAL

2022-12-21 14:23 UTC, tybritten approved these changes
LGTM

2023-01-04 17:02 UTC, merged