Add an "affects" field to roles, which shows which resource types a role is relevant for
pachyderm/pachyderm pull request #8954
Opened 2023-06-16 23:07 UTC by jrockway

Design: https://www.notion.so/2023-06-15-Returning-roles-in-a-user-friendly-way-2ff2947291fe4c06ac83a322ac2c123c

2023-06-17 02:01 UTC, albscui requested changes

2023-06-17 02:01 UTC, albscui commented on src/server/auth/server/roles.go
> +		Affects: []auth.ResourceType{auth.ResourceType_CLUSTER, auth.ResourceType_PROJECT},
I don't think project level roles (project viewer, writer, or owner) affects CLUSTER resource type.

2023-06-17 02:16 UTC, jrockway commented on src/auth/auth.proto
> +  // Resources this role can be applied to (for example, you can't apply ClusterAdmin to a repo.)
I think "applies_to" is the field name we're both looking for.  What do you think?

2023-06-17 02:16 UTC, jrockway commented on src/server/auth/server/roles.go
> +		Affects: []auth.ResourceType{auth.ResourceType_CLUSTER, auth.ResourceType_PROJECT},
Good point.

2023-06-19 16:59 UTC, albscui reviewed
Overall, I think this design makes sense. My issue is that I fear we are still not 100% concrete with the words we use: `applies to`, `affects`, `scopes`, `relevant`.

Essentially, we want the ability to answer:
- "what resources types can this role be attached to?", relevant at role binding creation/modification time.
    - this leverages the `scopes`  field
    - because scopes is a noun, we sometimes want to use verbs to describe the relationship between a role and a resource that captures the meaning of scope. This is where I disagree with the word `applies to`. I think `applies to` can be easily confused with `affects`. This is why I advocate for something like `attached to`.
- "what resources types does this role affect during authorization checks?"
    - this leverages the `affects` field, perfect 👍
- Overall, think we should not use the words `applies to` or `relevant`.

Lastly, instead of `scopes` and `affects`, which is a noun and verb respectively, we should be consistent, and use both nouns, or both verbs. I prefer using verbs, because they describe the relationships between two nouns, in this case `role -- verb --> resource`. I think instead of `scopes` we can use something like `can_attach_to`. However this is just a nitpick.

2023-06-21 23:32 UTC, jrockway commented
This has been dramatically reworked.  Well, not dramatically.  But the fields are "can be applied to" and "returned for".  "can be applied to" is what we thought ResourceType meant, but it was never actually used for that.  It's nice documentation to keep around, though, because eventually we will use it.  "returned for" is what we actually care about on this issue.

I did fix the project* roles to not be returned_for the cluster.

2023-06-22 02:19 UTC, albscui reviewed
LGTM!

2023-06-22 02:19 UTC, albscui commented on src/auth/auth.proto
> +  // Resources this role can be bound to.  For example, you can't apply clusterAdmin to a repo, so
Nice comments!

2023-06-22 02:19 UTC, albscui approved these changes

2023-06-22 03:38 UTC, merged